<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cellTable</name>
   <tag></tag>
   <elementGuidId>89751005-45da-4a28-9cc4-842522ee662b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
