<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>placeholer</name>
   <tag></tag>
   <elementGuidId>bea35039-f257-4481-8fdd-8ef22b77bb3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nz-select-placeholder[text()='${text}']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
