<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectLeasingStatus</name>
   <tag></tag>
   <elementGuidId>35225624-925d-4da7-acbb-573c82a43c58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nz-select[@formcontrolname=&quot;leasingStatus&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
