<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Building</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d60fe084-4d14-4434-a00c-b0b4f158f460</testSuiteGuid>
   <testCaseLink>
      <guid>33ab9225-8e9e-4ca9-8f9f-888895e1ec82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Buildings/Building/BuildingsList</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ab5a3c1-7a89-4edb-bf82-089790853b5a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5766d225-4a65-47bc-ac6d-b70bc626eb83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Buildings/Building/SearchBuilding</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1d8184f8-d40f-4721-b25b-6c6f30345f1a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Web/Building/SearchBuilding</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cc96e5a-86af-4dba-a049-faf7a7d82a27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>baf8cdc0-6bcd-419e-ab0f-311ac3f65811</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9cb9ee3-6273-431f-9f5f-aea6f52f7f61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90f2606d-d99f-4d19-bc42-d0f8652d2bda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a2cab19-2a08-4d32-b4ad-3337660448ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75b34d58-1ffa-4899-929d-e013fde99a8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5aa8d4d0-8ac6-4ad8-8ead-51b22ead2be9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a0097bf-8dd4-42ab-8e41-90044859f119</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bd9055c-a3e1-42f1-9d83-bf88905e173d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ace1a05-2692-4c01-978f-a0079da5c508</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1d8184f8-d40f-4721-b25b-6c6f30345f1a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>value</value>
         <variableId>897351c7-96b1-4998-b5d0-2dddb66c1fa3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1d8184f8-d40f-4721-b25b-6c6f30345f1a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>50b7efb9-74c8-4e41-a33f-48a69725234e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1d8184f8-d40f-4721-b25b-6c6f30345f1a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expected</value>
         <variableId>450c484b-ffa4-4e9d-b1c2-65d90dbbb3dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e4d0e49-cf1d-4bca-96e9-30b42040eafb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c13b794d-fbde-4c28-bcf8-53bf80e5a7b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>792290ab-2eb1-494a-aedc-742b9b20b93e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Buildings/Building/ValidatePagination</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f71a721d-5907-4067-937d-d7666eec0e41</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Web/Building/PaginationBuildingList</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f71a721d-5907-4067-937d-d7666eec0e41</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>row</value>
         <variableId>9246b789-2151-435e-a5e1-5199a101fe00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f71a721d-5907-4067-937d-d7666eec0e41</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>1eb330bd-bb53-464e-b2c4-affb6a6156ba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9890307a-b2a9-4c2b-93a0-6eefe3500653</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Buildings/Building/ValidateTable</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c13b794d-fbde-4c28-bcf8-53bf80e5a7b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64ce2540-088f-425a-a3bf-6eb2997ea926</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e51d3860-0e1d-40d3-99d9-abd0db4f9ac7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4e3c365-ce5b-42fb-924e-88c6a47edd33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ffbe762-0c33-4096-9161-43c75d7f2c62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b12c9831-50d8-4621-b7dc-8885c7b07b7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0b79b87-ecaf-4cb5-80a7-64f035a71c81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27b289a5-ae6f-4102-8f9d-c46ccbb49073</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b91bcb2a-4d39-44b4-9c52-343ef02f89b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>47c518fc-3207-4bb5-a09c-71c5d3ea9096</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Buildings/Building/ActiveAndInactiveBuilding</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b8a39ef3-e184-4bb7-ad03-b4c96b54e285</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Web/Building/ActiveAndInactiveBuilding</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b8a39ef3-e184-4bb7-ad03-b4c96b54e285</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>buildingCode</value>
         <variableId>07e0dbe0-483b-4d5c-8994-9dbf248ae611</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b8a39ef3-e184-4bb7-ad03-b4c96b54e285</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>7ff056b0-2981-46a7-91e1-0cfa34f6b2d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa14999d-27bc-4e8e-8417-37bd94f4d4b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ceef7d65-c27e-42f4-a1ac-318eb64cf1e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e03f823-d1a0-4c27-9688-54771aa8597b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c8e06108-6b91-4883-9621-484aab272b9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Buildings/Building/VerifyVisiableCreateNewBuilding</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1625972-2066-452e-8e29-638de6157899</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58cd758b-7a24-4fb2-91ed-7dab76ea1db6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25398f6e-329a-4c84-855b-e89da3230575</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cee8ada1-8937-481a-96eb-eeda996202ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b069129c-1291-44ef-9f90-c30bf1db26cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e775a0c7-c322-4195-9ec0-4e16d1ba6b0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a4baa60-2df0-43cc-a243-979d5a5554c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88df7f2e-9c61-429a-8947-c3614e5ae745</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6e692aa-b705-4cfa-930d-c4a9c1eedbdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b29b7f36-d9ea-44de-90f0-3c136f049381</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86c8be67-d54c-4412-bd88-dcb8062785f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d327dc0c-1d66-4593-be64-ce68445373b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3247eac4-1580-45cb-981f-2dbfacc2f004</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>006a5a14-b625-44bb-9bad-8b9c7c02573d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8e89d9e-225c-4e0f-b863-e1afe0450124</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09bfece7-282e-4a9e-9bf4-0f002ae463a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa99974a-58d3-4b42-bfea-464b0b6f3a68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36da6f23-151e-4275-bdae-cc271f078301</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12811af0-2adb-437a-9e3b-993fcb491e0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13cdba67-683c-47bb-8527-c2ec20256c7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5871d379-972f-4b0b-ba93-c5ee11649a4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2b03c45-b66b-4aa6-98ec-f2d7d7ff650f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea601b2a-8d4c-4e6a-8885-45b2afc16d6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d226edf9-7a6d-487f-a271-c387d47210a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82067add-304a-4d0b-90b4-1ec06a81ac6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Buildings/Building/CreateBuilding</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0eed53c6-eef7-431f-9207-100921a3ef7f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Web/Building/CreateBuilding</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0eed53c6-eef7-431f-9207-100921a3ef7f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>buildingCode</value>
         <variableId>1c7ff189-ca23-4c78-8d26-3752d26da83d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0eed53c6-eef7-431f-9207-100921a3ef7f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>buildingName</value>
         <variableId>83d3edc3-3a24-49a0-8667-c9f51856e0e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0eed53c6-eef7-431f-9207-100921a3ef7f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>floor</value>
         <variableId>57428408-47b6-4aef-a8b8-4dfe9fd0691f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0eed53c6-eef7-431f-9207-100921a3ef7f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>area</value>
         <variableId>dd8ccfe1-81f0-446b-99cd-51d7a1499447</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0eed53c6-eef7-431f-9207-100921a3ef7f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>address</value>
         <variableId>1cc11a58-b1e3-4cf6-bc15-f2945d2c1fe1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0eed53c6-eef7-431f-9207-100921a3ef7f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>statusBuilding</value>
         <variableId>131b55cb-2b1d-4278-95d4-7e15770844dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0eed53c6-eef7-431f-9207-100921a3ef7f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>note</value>
         <variableId>b4afeca4-a068-4dab-b9d6-2fbeb134642d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0eed53c6-eef7-431f-9207-100921a3ef7f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>f5cb77a4-ef8d-452c-ba90-52ee59d211d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e97d326-0abf-4364-9749-ca925536ac8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c1f0ba4-4a08-4791-856f-3e9990795764</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0eed53c6-eef7-431f-9207-100921a3ef7f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>message</value>
         <variableId>c72f1ea4-4eb7-401c-b0c9-e93b6de0b49d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af266fb6-1755-4ccd-98de-e6fd9edaa07a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Buildings/Building/VerifyVisiableCreateFloor</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1625972-2066-452e-8e29-638de6157899</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58cd758b-7a24-4fb2-91ed-7dab76ea1db6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c7ff189-ca23-4c78-8d26-3752d26da83d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83d3edc3-3a24-49a0-8667-c9f51856e0e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd8ccfe1-81f0-446b-99cd-51d7a1499447</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cc11a58-b1e3-4cf6-bc15-f2945d2c1fe1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>131b55cb-2b1d-4278-95d4-7e15770844dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4afeca4-a068-4dab-b9d6-2fbeb134642d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e97d326-0abf-4364-9749-ca925536ac8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c1f0ba4-4a08-4791-856f-3e9990795764</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c72f1ea4-4eb7-401c-b0c9-e93b6de0b49d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a85fe113-cec2-4398-b4a0-1c3c66fd10ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa488b37-028d-42d0-a500-84b2d9f202c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de82ade9-d5e5-4e76-b16f-682d8b193076</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59ecd70a-69dc-4fc6-bfe7-cdf75883a600</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db0a60aa-62ea-452c-afb7-9415a2743018</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3976911-7c93-44d2-bbfb-ee8bb3050d32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a86ed1ad-a757-4846-b04c-b062e3accd5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d15ded56-9001-4ba8-8a2c-b44af92468eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03434cdb-1028-47a5-804c-ff3e6ab4ed36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a42075b-8d6a-4bbb-9f9f-3d48250fb4fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24614770-1707-4d51-866d-a601a41686c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e2aef57-859d-4818-b419-55c04fadbe92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a78a5bf0-1430-4ace-9060-f53e032cdac8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d435c5f1-bb68-4f05-b573-a1ed39b2ac5f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8bd34eae-9a61-41b8-8d37-2c5913c1746f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Buildings/Building/CreateFloor</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ce9e766-9e01-4e7a-b63f-a7ac39fc1a04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b940a5f-1e95-48f9-8125-871fafe2bffe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77a1be2f-fdd8-4b41-bccc-bbfdf1205847</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56da9782-c14c-448a-8815-78f13df38abb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Buildings/Building/EditFloor</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a2b74dc-bba3-42bf-ba4c-7a58fb7f2333</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1545bb4c-75c0-4b57-af85-f8e4fc9f091e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cac443d3-8f6e-4aea-abf3-e23f4c01938a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc52cec5-2fa9-41bb-8d39-93fb948d7d01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a1d689a-67e9-4863-8e8c-f3c58ce45502</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d56e80b0-2b33-488e-a2a6-88162287acd6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Buildings/Building/DeleteFloor</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e260ea9f-8391-4ad1-83b3-85e890e67f3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a22a13f-a8d9-44d1-8714-dbf4694a8d15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a049f7cb-af44-4df1-8771-6d640761559d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d4cdb05-87e1-4e96-9d77-2288ed234412</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72352a90-133b-4b7b-b72a-de12cc9f6685</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3365676-e50b-40d4-b469-1d5c2af8afc9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web/Buildings/Building/EditBuilding</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b03da1d4-1ca9-43ed-b249-f6f77c62a057</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Web/Building/EditBuilding</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b03da1d4-1ca9-43ed-b249-f6f77c62a057</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>buildingName</value>
         <variableId>060a827b-055e-4fb6-bc49-ba301827bd19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b03da1d4-1ca9-43ed-b249-f6f77c62a057</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>floor</value>
         <variableId>31948a41-8f75-4246-ad47-6fdf789b1008</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b03da1d4-1ca9-43ed-b249-f6f77c62a057</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>area</value>
         <variableId>a9577f4d-59ff-412f-b893-0aa541ff71aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b03da1d4-1ca9-43ed-b249-f6f77c62a057</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>address</value>
         <variableId>d36c4283-0a04-4390-948e-d9abd593f192</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b03da1d4-1ca9-43ed-b249-f6f77c62a057</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>statusBuilding</value>
         <variableId>6c0dd84e-e6bf-44f0-8539-0befd655e6bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b03da1d4-1ca9-43ed-b249-f6f77c62a057</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>note</value>
         <variableId>7ee6f015-2c40-413e-9f15-8571d3a6bd79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b03da1d4-1ca9-43ed-b249-f6f77c62a057</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>message</value>
         <variableId>6f1f3b26-2282-4e92-b162-4758a983f8f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b03da1d4-1ca9-43ed-b249-f6f77c62a057</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>326c95c5-cc84-47b2-9c7d-1514aef2465c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19df4fc8-a3d6-4097-992c-28d246367643</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7bc5d5d-a2b3-4b63-8063-9f8cbed82785</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
