<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Customer</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5d77cec2-6f1e-46d0-b3ae-9c5b86ad3e80</testSuiteGuid>
   <testCaseLink>
      <guid>51c62602-77c3-462d-a3aa-1f85b27b2829</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Customers/CustomersList</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>faf79c6a-7812-4946-af10-67ba8a8e4f36</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a169fa2-ab14-4094-a09a-85b2daf64f94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Customers/ActiveAndInactiveAccount</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9e1b9046-0e4c-45ee-8e27-f08a4fe107f0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Web/Customers/ActiveAndInactiveAccount</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>630b0c0f-d51f-47e8-9f77-889c8f0d561d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b69c4163-ea74-42d9-8682-b092dc2b92fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>303a9dec-52f3-4f3d-b374-d6477f392e51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92feef5c-b979-40c3-aacc-f0af8cb62cfa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>275f6a77-197c-4fbf-95ba-e3d46eef23e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9e1b9046-0e4c-45ee-8e27-f08a4fe107f0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lockStatus</value>
         <variableId>000967a2-dc51-4db2-95ac-b3e7537f4d52</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9732b153-fb67-4f6e-9e39-80588201c8f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Customers/SearchCustomers</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>fb863a4b-b81e-44aa-a809-85cd00bde25f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Web/Customers/SearchCustomers</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>fb863a4b-b81e-44aa-a809-85cd00bde25f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>textSearch</value>
         <variableId>68e120e8-d22f-4e2b-8d78-150b67a0df8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fb863a4b-b81e-44aa-a809-85cd00bde25f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expected</value>
         <variableId>8621716b-7a73-446d-b0a5-1d0f39c65da6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fb863a4b-b81e-44aa-a809-85cd00bde25f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>09c3fdd8-7ed4-4f77-9d12-066336e861c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0a85d25-01be-4239-b9f0-23f70d3ae9a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>faf79c6a-7812-4946-af10-67ba8a8e4f36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>674d6a70-13c3-444e-b071-1345d9956d0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9a02388-a740-47a8-a8d7-f967108b5944</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>729b0407-8539-4309-b01d-ca76886650a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2e50f86-18ec-4849-9f07-22bc17a27309</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>029caf8c-6709-413d-b0aa-767e2ab98caa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fda84cc-9669-4ce8-8d39-ccfe9d5ad6dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0082f13-31d0-4e48-8768-f5b3a9484d81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfdf5894-2024-4b3c-bf4e-9effbf2d8226</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bd9055c-a3e1-42f1-9d83-bf88905e173d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97bdb22b-a7b0-4cd4-908b-926ce621b686</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Customers/AdvancedSearch</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>960a2e4c-6c71-4ac0-988a-978bd31df2c0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Web/Customers/AdvancedSearch</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>960a2e4c-6c71-4ac0-988a-978bd31df2c0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>status</value>
         <variableId>7729de2a-c842-4514-b18a-80888cdf0b9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f6bfbe1-720b-413f-9094-86991bf6622e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7051a5b-046c-4a34-aec3-e4f4175aaf5c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f22c416-9cee-4671-843c-a36afecb1c88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Customers/ValidatePagination</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b6484206-f22f-44eb-95ed-bc47e7869284</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Web/Customers/ValidatePagination</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b6484206-f22f-44eb-95ed-bc47e7869284</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>numberRow</value>
         <variableId>0c5a1991-3911-46f8-b388-d27c1399e646</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1aa66737-58fa-4afb-8e74-d31901d85e96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b2915f3-4ba5-466d-a3b6-988fbc6c93a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Customers/VerifyVisibleCreateNewCustomerInformation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df64f075-658a-464b-a380-22891885b0f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6800bb68-ff19-4eb0-af1d-68f0abcf0dbf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce1d8b26-14ee-47fa-a84e-2278dda9bdb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc72ae08-843b-4373-a0ef-c2c5deb9f821</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ce8845a-d9fe-4fdd-b103-8878c637404c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6001e64c-3035-4f7c-9e79-23b91e80e38c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed475d1e-6ab6-4388-ab59-ec0dc3e39946</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28a2d205-2e7e-478e-83ff-472482405655</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc582390-f483-419f-9ccb-105b575a9185</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d61b40c-b669-4386-aeac-8fb6cadbad11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e04a8288-5bd1-4618-929e-fb0c514e77d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43a945b0-7e75-4f4e-982b-5995a57c884e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9d7ccd9-89ce-4eaf-b98a-902bcc557000</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c067a35-99b9-40ab-a4af-9e762042d883</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81bd3abb-586b-4409-b471-0d5e40b00cf4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d231da42-19b0-42f5-bfaa-dab2e7fdf779</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c15b37ec-f058-432b-b011-c2fe84722b71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>087ea9ca-3c69-4d82-aa9b-4695372d6316</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8150c400-39b7-4fb7-829f-a6877f9a2e89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>524f6202-79be-40f5-8881-895727d44038</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a858473d-c222-4f14-9558-0236ad9c737e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1770a81a-bd8f-49cb-a2bd-975e097814db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c77664a-971f-4c91-8acc-79506eb35f18</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d5cf16a8-d9a8-4cd5-b8c9-fd2fbd2828c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Customers/CreateNewCustomerInformation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2181481b-8ea6-4acf-8826-c86e6a3efdf9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Web/Customers/CreateNewCustomerInformation</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2181481b-8ea6-4acf-8826-c86e6a3efdf9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>businessRegistrationCode</value>
         <variableId>9b7b2ee6-99b5-4615-8f35-84f6f3b78842</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2181481b-8ea6-4acf-8826-c86e6a3efdf9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company</value>
         <variableId>18c94e88-acb7-4be8-8f8b-a24653ba37bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2181481b-8ea6-4acf-8826-c86e6a3efdf9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>231103dd-20ac-438a-818e-cc9f8cfaa482</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2181481b-8ea6-4acf-8826-c86e6a3efdf9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>address</value>
         <variableId>2fa5a19f-b0fe-4dbf-83d3-66f776bf5d7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2181481b-8ea6-4acf-8826-c86e6a3efdf9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>representative</value>
         <variableId>d109cd1b-156d-4cd8-906d-d5fcb8056105</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2181481b-8ea6-4acf-8826-c86e6a3efdf9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>phoneNumber</value>
         <variableId>c5117faa-397f-4c1e-8c5a-3f3cb04af1f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2181481b-8ea6-4acf-8826-c86e6a3efdf9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>foundingDate</value>
         <variableId>a419e3e3-0a65-4444-8ac8-4948af416d98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2181481b-8ea6-4acf-8826-c86e6a3efdf9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>type</value>
         <variableId>48ccdf6c-2af6-4fcf-8f60-e0b861c423f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2181481b-8ea6-4acf-8826-c86e6a3efdf9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>status</value>
         <variableId>d0f03c6c-c6ea-4299-9fd4-27b9424fd967</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2181481b-8ea6-4acf-8826-c86e6a3efdf9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>action</value>
         <variableId>bc86e976-0ad2-4441-9b4a-c135c4ba3b5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f4f8b62-3a7b-4e6a-b92a-039b8f893d33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2181481b-8ea6-4acf-8826-c86e6a3efdf9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>infor</value>
         <variableId>ef21af44-7685-40e1-958b-81be2349c8cb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>560f6c8d-a059-487a-ab9c-83dbe33350fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Customers/VerifyVisibleCreateCustomerContacts</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b7b2ee6-99b5-4615-8f35-84f6f3b78842</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18c94e88-acb7-4be8-8f8b-a24653ba37bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>231103dd-20ac-438a-818e-cc9f8cfaa482</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fa5a19f-b0fe-4dbf-83d3-66f776bf5d7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d109cd1b-156d-4cd8-906d-d5fcb8056105</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5117faa-397f-4c1e-8c5a-3f3cb04af1f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a419e3e3-0a65-4444-8ac8-4948af416d98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48ccdf6c-2af6-4fcf-8f60-e0b861c423f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0f03c6c-c6ea-4299-9fd4-27b9424fd967</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc86e976-0ad2-4441-9b4a-c135c4ba3b5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f4f8b62-3a7b-4e6a-b92a-039b8f893d33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef21af44-7685-40e1-958b-81be2349c8cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bd9055c-a3e1-42f1-9d83-bf88905e173d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1770a81a-bd8f-49cb-a2bd-975e097814db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>524f6202-79be-40f5-8881-895727d44038</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c94bc0a8-0589-4db7-8298-5057e9750d5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd40efd4-e426-40a1-8f46-bee10c59cf39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8eb5ad1c-8b40-4748-89fb-3a7fd7ab0956</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81bd3abb-586b-4409-b471-0d5e40b00cf4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d231da42-19b0-42f5-bfaa-dab2e7fdf779</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c15b37ec-f058-432b-b011-c2fe84722b71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4af244c-ac55-4414-aebb-58874f2be51b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f93d2d4-bcbc-4a65-b7c1-418c4594c213</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>483df07c-0d2e-441b-90ce-4d35958f31df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56a442cf-05b1-477c-b444-a9554f8685ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0724fab1-4108-4050-9579-c7bed6ae00de</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c058041e-cf79-4522-b5f7-bd597cac3f24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Customers/CreateCustomerContacts</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>719469dd-c411-4103-bd4b-48bfba23f2b8</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Web/Customers/CreateContactsCustomer</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b7b2ee6-99b5-4615-8f35-84f6f3b78842</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18c94e88-acb7-4be8-8f8b-a24653ba37bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>231103dd-20ac-438a-818e-cc9f8cfaa482</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fa5a19f-b0fe-4dbf-83d3-66f776bf5d7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d109cd1b-156d-4cd8-906d-d5fcb8056105</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5117faa-397f-4c1e-8c5a-3f3cb04af1f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a419e3e3-0a65-4444-8ac8-4948af416d98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48ccdf6c-2af6-4fcf-8f60-e0b861c423f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0f03c6c-c6ea-4299-9fd4-27b9424fd967</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc86e976-0ad2-4441-9b4a-c135c4ba3b5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f4f8b62-3a7b-4e6a-b92a-039b8f893d33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef21af44-7685-40e1-958b-81be2349c8cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bd9055c-a3e1-42f1-9d83-bf88905e173d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>719469dd-c411-4103-bd4b-48bfba23f2b8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>fullNameContact</value>
         <variableId>8895eb90-bd3b-481c-893b-782d8f115c2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>719469dd-c411-4103-bd4b-48bfba23f2b8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>phoneNumberContact</value>
         <variableId>d652478e-fc01-4fdf-80f0-03d5d9f35d17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>719469dd-c411-4103-bd4b-48bfba23f2b8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>emailContact</value>
         <variableId>28bb9f85-00f9-4087-95d8-526ad64ee41c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>719469dd-c411-4103-bd4b-48bfba23f2b8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>inforContact</value>
         <variableId>a7cf621b-154a-4e0c-b6ef-50ffd1cff03b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>719469dd-c411-4103-bd4b-48bfba23f2b8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>actionContact</value>
         <variableId>cc85ce74-9ee7-4105-8833-095273a75153</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9f750a8f-9914-44fa-8fb6-28a736796e1c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Customers/VerifyVisibleCreateNewInformationRent</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b7b2ee6-99b5-4615-8f35-84f6f3b78842</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18c94e88-acb7-4be8-8f8b-a24653ba37bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>231103dd-20ac-438a-818e-cc9f8cfaa482</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fa5a19f-b0fe-4dbf-83d3-66f776bf5d7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d109cd1b-156d-4cd8-906d-d5fcb8056105</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5117faa-397f-4c1e-8c5a-3f3cb04af1f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a419e3e3-0a65-4444-8ac8-4948af416d98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48ccdf6c-2af6-4fcf-8f60-e0b861c423f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0f03c6c-c6ea-4299-9fd4-27b9424fd967</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc86e976-0ad2-4441-9b4a-c135c4ba3b5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f4f8b62-3a7b-4e6a-b92a-039b8f893d33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef21af44-7685-40e1-958b-81be2349c8cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bd9055c-a3e1-42f1-9d83-bf88905e173d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1770a81a-bd8f-49cb-a2bd-975e097814db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>524f6202-79be-40f5-8881-895727d44038</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c94bc0a8-0589-4db7-8298-5057e9750d5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4af244c-ac55-4414-aebb-58874f2be51b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f93d2d4-bcbc-4a65-b7c1-418c4594c213</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>483df07c-0d2e-441b-90ce-4d35958f31df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56a442cf-05b1-477c-b444-a9554f8685ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0724fab1-4108-4050-9579-c7bed6ae00de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71f88867-bf77-44f5-8532-f144de7af081</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aae623bd-ce2c-4437-a5fa-aac70955092b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b7c30d9-094c-441f-9b10-c6f5130ee513</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db5f4121-f74f-4460-9ab4-85a05d5004d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9298e11-b855-4475-821c-0f9c35346618</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25f03e99-6efe-4b89-a08c-3145867256d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0c2d8e9-5862-4853-9671-b02ee7e298ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d68a2c7-5aa7-466a-862e-085c85a31027</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Customers/CreateInformationRent</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c96350bb-7305-44c0-a743-32d59ad4ffad</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Web/Customers/CreateInformationRent</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c96350bb-7305-44c0-a743-32d59ad4ffad</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>status</value>
         <variableId>92abaccd-f233-4b52-8da4-4ed09de57f4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c96350bb-7305-44c0-a743-32d59ad4ffad</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>action</value>
         <variableId>b96c655a-6149-4d4a-9b65-225618929cd0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f4f8b62-3a7b-4e6a-b92a-039b8f893d33</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39318fd9-3374-4186-a8aa-c46938e5495b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Customers/EditCustomerInformationRent</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3a117c75-0721-4c94-b7ab-486fc18a3f4a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Web/Customers/EditCustomerInformationRent</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>3a117c75-0721-4c94-b7ab-486fc18a3f4a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>action</value>
         <variableId>2fe4f836-c523-4d31-b625-8aa22f7fcdb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3a117c75-0721-4c94-b7ab-486fc18a3f4a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>status</value>
         <variableId>3b179e91-2650-4c15-95b2-f465b6229605</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4114121e-1476-4dc6-9d73-83b568b5ce5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Customers/EditCustomerInformation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4c0a0677-0e19-4a6b-98d7-d8f6075c4c6b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Web/Customers/EditCustomerInformation</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8150c400-39b7-4fb7-829f-a6877f9a2e89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>524f6202-79be-40f5-8881-895727d44038</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a858473d-c222-4f14-9558-0236ad9c737e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1770a81a-bd8f-49cb-a2bd-975e097814db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c77664a-971f-4c91-8acc-79506eb35f18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>001f6a08-bace-4523-94a4-0edb039f1a92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6e887ed-e46b-474b-9eb3-8e31515c3412</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10a9d652-6599-4cd6-bbf5-a0bbf3c3a49a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4c0a0677-0e19-4a6b-98d7-d8f6075c4c6b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>status</value>
         <variableId>ca1c9699-f5a3-4f25-85af-ab0a45d6e41b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4c0a0677-0e19-4a6b-98d7-d8f6075c4c6b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>action</value>
         <variableId>f7310b33-cb80-45ad-8251-5dc9c036638a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9066991e-15a5-4b36-b57b-c66661b65fab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Web/Customers/EditCustomerContact</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
