<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>smallWarning</name>
   <tag></tag>
   <elementGuidId>8576cf07-c1eb-41a8-a77f-c56e35c22d63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//small</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
